axis:
    audit:
        message:
            url: http://localhost:8080
dynamo:
    access:
        key: ${AWS_ACCESS_KEY}
    db:
        region: ap-south-1
    secret:
        key: ${AWS_SECRET_KEY}
    server:
        endpoint: dynamodb.ap-south-1.amazonaws.com
encryption:
    master:
        key: tesbksdag-tweri-65767
management:
    endpoint:
        metrics:
            enabled: true
    endpoints:
        web:
            exposure:
                include: info,health,prometheus
    metrics:
        export:
            prometheus:
                enabled: true
spring:
    axis:
        datasource:
            driver-class: org.postgresql.Driver
            password: Axis@2024
            url: jdbc:postgresql://192.168.2.207:5433/axis_mw?serverTimezone=UTC
            username: axis
    cms:
        datasource:
            driver-class: org.postgresql.Driver
            password: Axis@2024
            url: jdbc:postgresql://192.168.2.207:5433/strapi?serverTimezone=UTC
            username: axis
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    main:
        allow-bean-definition-overriding: true
