aggregator:
    internal:
        base:
            url: http://localhost:8080/aggregater-service
        get:
            scheme:
                service:
                    url: /GetSchemeInFolio
api:
    config:
        agent:
            id: SELF/DIRECT
        branch:
            mobile: MA88
            web: WB99
        fund: 128
        id: id
        kfin:
            tech:
                password: RFBVcmhEeC4rQXJZ-xb8Sn6oQcxM=
                username: KCPLBGFGI7PW
        sip:
            type: Online
        source: MSIL
app:
    axis:
        drop-link:
            service:
                base:
                    url: http://localhost:8081/droplink-services/droplink
                get:
                    url: /${id}/v1
                update:
                    url: /update/v1
fetch:
    otp:
        service:
            url: /fetchOTP
generate:
    otp:
        service:
            url: /generateOTP
generte:
    otp:
        base:
            url: https://localhost:dummy.com
kfintech:
    additional:
        purchase:
            service:
                url: /MultiCart
    base:
        url: https://axismfservicesuat.kfintech.com/AXISMFMSILServices/AXISMFAPIV2.svc
    confirm:
        mcart:
            service:
                url: /ConfirmMulticart
    get-folio-details:
        service:
            url: /GetFolioDetails
    get-token-pan-login:
        service:
            url: /GetTokenPANLogin
    purchase:
        mcart:
            service:
                url: /NewPurchaseMulticart
management:
    endpoint:
        metrics:
            enabled: true
    endpoints:
        web:
            exposure:
                include: info,health,prometheus
    metrics:
        export:
            prometheus:
                enabled: true
resend:
    otp:
        service:
            url: /resendOTP
spring:
    axis:
        datasource:
            driver-class: org.postgresql.Driver
            password: Axis@2024
            url: jdbc:postgresql://192.168.2.207:5433/axis_mw?serverTimezone=UTC
            username: axis
    cms:
        datasource:
            driver-class: org.postgresql.Driver
            password: Axis@2024
            url: jdbc:postgresql://192.168.2.207:5433/strapi?serverTimezone=UTC
            username: axis
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    main:
        allow-bean-definition-overriding: true
verify:
    otp:
        service:
            url: /verifyOTP

dynamo:
    access:
        key: ${AWS_ACCESS_KEY}
    db:
        region: ${AWS_REGION}
    secret:
        key: ${AWS_SECRET_KEY}
    server:
        endpoint: http://localhost:9056    

            
